import React from 'react';
import { Box, Typography } from '@mui/material';
import ScrollReveal from './ScrollReveal';

/**
 * Footer links to the static, JS-free companion pages generated by
 * scripts/generate-seo-pages.js.
 *
 * These are real document navigations rather than SPA routes: the pages are
 * plain HTML served directly by Firebase Hosting. Linking them from the app
 * is what keeps them out of the orphaned-URL bucket in Search Console.
 */

const PAGES = [
  { href: '/about/', label: 'About' },
  { href: '/publications/', label: 'Publications' },
  { href: '/projects/', label: 'Projects' },
];

const linkSx = {
  color: 'rgba(255,255,255,0.55)',
  fontSize: '0.8rem',
  textDecoration: 'none',
  transition: 'color 0.3s ease',
  '&:hover, &:focus-visible': { color: '#d4a853' },
};

const SiteFooterNav = () => (
  <ScrollReveal direction="blur" delay={150}>
    <Box
      component="nav"
      aria-label="Site pages"
      sx={{
        mt: 8,
        display: 'flex',
        justifyContent: 'center',
        flexWrap: 'wrap',
        gap: 2.5,
      }}
    >
      {PAGES.map((page) => (
        <Typography key={page.href} component="a" href={page.href} sx={linkSx}>
          {page.label}
        </Typography>
      ))}
    </Box>
  </ScrollReveal>
);

export default SiteFooterNav;
